
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`<url>`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls:
    secretName: <your-tls-secret-name>
